<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "nl_dmailsubscription"
 *
 * Auto generated by Extension Builder 2018-05-22
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'NL Dmail Subscription',
    'description' => 'Direct Mail subscription by netzlabor coding GmbH',
    'category' => 'plugin',
    'author' => 'Maksym',
    'author_email' => 'maksim.chubin@netzlabor-coding.de',
    'state' => 'alpha',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '10.4.2',
    'constraints' => [
        'depends' => [
            'typo3' => '10.4.0-10.4.99',
            'tt_address' => '4.0.0-',
            'direct_mail' => '7.0',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
